import { afterEach, describe, expect, it } from "vitest";
import { promises as fs } from "fs";
import os from "os";
import path from "path";
import { getMetaDataFromFile } from "../../src/routes/slicing/slicing.service";

/**
 * Print time and filament usage come back as the X-Print-Time-Seconds /
 * X-Filament-Used-G / X-Filament-Used-Mm response headers, which is where
 * Bambuddy reads a slice's cost and duration from.
 *
 * The parser understood only OrcaSlicer's spelling, so every slice through
 * the BambuStudio sidecar answered `X-Filament-Used-G: 0`. Print time was
 * right, which is exactly what hid it -- the headers looked populated.
 *
 * Both dialects are pinned here with real header blocks captured from
 * OrcaSlicer 2.4.2 and BambuStudio 02.07.01.62 slicing the same Cube.stl,
 * which is why both report 0.72 g.
 */

const ORCA_HEADER = `; generated by OrcaSlicer 2.4.2 on 2026-08-10 at 10:26:07
; total layer number: 50
; filament used [mm] = 237.97
; filament used [cm3] = 0.57
; filament used [g] = 0.72
; total estimated time: 16m 7s
`;

const BAMBU_HEADER = `; HEADER_BLOCK_START
; BambuStudio 02.07.01.62
; model printing time: 10m 17s; total estimated time: 16m 33s
; total layer number: 50
; total filament length [mm] : 240.69
; total filament volume [cm^3] : 578.93
; total filament weight [g] : 0.72
; HEADER_BLOCK_END
`;

// The config block every slicer appends. Its filament_* keys are the reason
// the patterns anchor on the full label rather than on "filament".
const CONFIG_BLOCK_NOISE = `
; CONFIG_BLOCK_START
; filament_density = 1.25
; filament_diameter = 1.75
; filament_change_length = 10
; filament_retract_length_nc = 10
; CONFIG_BLOCK_END
`;

const created: string[] = [];

async function gcodeFile(content: string): Promise<string> {
  const dir = await fs.mkdtemp(path.join(os.tmpdir(), "gcode-meta-"));
  const file = path.join(dir, "plate_1.gcode");
  await fs.writeFile(file, content);
  created.push(dir);
  return file;
}

afterEach(async () => {
  await Promise.all(
    created.splice(0).map((dir) => fs.rm(dir, { recursive: true, force: true })),
  );
});

describe("G-code metadata extraction", () => {
  it("reads OrcaSlicer's header", async () => {
    const data = await getMetaDataFromFile(
      await gcodeFile(ORCA_HEADER + CONFIG_BLOCK_NOISE),
    );

    expect(data.filamentUsedG).toBeCloseTo(0.72);
    expect(data.filamentUsedMm).toBeCloseTo(237.97);
    expect(data.printTime).toBe(16 * 60 + 7);
  });

  it("reads BambuStudio's header", async () => {
    const data = await getMetaDataFromFile(
      await gcodeFile(BAMBU_HEADER + CONFIG_BLOCK_NOISE),
    );

    // The regression: these were 0 for every BambuStudio slice.
    expect(data.filamentUsedG).toBeCloseTo(0.72);
    expect(data.filamentUsedMm).toBeCloseTo(240.69);
    expect(data.printTime).toBe(16 * 60 + 33);
  });

  it("is not fooled by the config block's filament_* keys", async () => {
    // A header-less file must report nothing rather than picking up a
    // retract length and calling it grams.
    const data = await getMetaDataFromFile(
      await gcodeFile(CONFIG_BLOCK_NOISE),
    );

    expect(data.filamentUsedG).toBe(0);
    expect(data.filamentUsedMm).toBe(0);
    expect(data.printTime).toBe(0);
  });

  it("handles a multi-hour estimate", async () => {
    const data = await getMetaDataFromFile(
      await gcodeFile("; total estimated time: 1d 2h 3m 4s\n"),
    );

    expect(data.printTime).toBe(86400 + 2 * 3600 + 3 * 60 + 4);
  });

  it("understands the PrusaSlicer-descended spelling", async () => {
    const data = await getMetaDataFromFile(
      await gcodeFile("; estimated printing time (normal mode) = 2h 5m 1s\n"),
    );

    expect(data.printTime).toBe(2 * 3600 + 5 * 60 + 1);
  });

  it("returns zeroes for a file that is not G-code", async () => {
    const dir = await fs.mkdtemp(path.join(os.tmpdir(), "gcode-meta-"));
    created.push(dir);
    const file = path.join(dir, "notes.txt");
    await fs.writeFile(file, ORCA_HEADER);

    const data = await getMetaDataFromFile(file);

    expect(data).toEqual({
      printTime: 0,
      filamentUsedG: 0,
      filamentUsedMm: 0,
    });
  });
});
